server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/choihyewon/Desktop/Work/git-local-repo
        git:
          uri: https://github.com/hyewon218/spring-cloud-config.git

